### ISSUE TITLE
Unable to install Kibana 3.1.0 from version 0.1.9

### ISSUE THREAD

**Issue by dpresling** [realityforge/chef-kibana#53] opened 2015-07-30 23:33 UTC
Getting the following error when trying to build. Last successful build was April 28, 2015.

Chef omnibus = 11.16.4

Local attributes file:

default[:kibana][:version] = '3'
default[:kibana][:kibana3_version] = '3.1.0'
default[:kibana][:checksum] = '059a4b6b507b9ff771901d12035e499b0e8d1cae7d9e5284633e19da6c294e07'
default[:nginx][:default_site_enabled] = false

Output of Test Kitchen:

       Recipe: kibana::kibana3
         * ark[kibana] action install
           * directory[/usr/local/kibana-3.1.0] action create
             - create new directory /usr/local/kibana-3.1.0
           * remote_file[/tmp/kitchen/cache/kibana-3.1.0.tar.gz] action create
             - create new file /tmp/kitchen/cache/kibana-3.1.0.tar.gz[2015-07-30T23:28:30+00:00] WARN: remote_file[/tmp/kitchen/cache/kibana-3.1.0.tar.gz] cannot be downloaded from https://download.elasticsearch.org/kibana/kibana/kibana-2-linux-x64.tar.gz: 404 "Not Found"

             ================================================================================
             Error executing action `create` on resource 'remote_file[/tmp/kitchen/cache/kibana-3.1.0.tar.gz]'
             ================================================================================

             Net::HTTPServerException
             ------------------------
             404 "Not Found"

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/ark/providers/default.rb

       45:   remote_file new_resource.release_file do
       46:     Chef::Log.debug('DEBUG: new_resource.release_file')
       47:     source new_resource.url
       48:     checksum new_resource.checksum if new_resource.checksum
       49:     action :create

       51:   end
       52:

             Compiled Resource:
             ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/ark/providers/default.rb:45:in `block in class_from_file'

             remote_file("/tmp/kitchen/cache/kibana-3.1.0.tar.gz") do

        action [:create]
        retries 0
        retry_delay 2
        guard_interpreter :default
        path "/tmp/kitchen/cache/kibana-3.1.0.tar.gz"
        backup 5
        atomic_update true
        source ["https://download.elasticsearch.org/kibana/kibana/kibana-2-linux-x64.tar.gz"]
         use_etag true
        use_last_modified true
        cookbook_name "kibana"
        checksum "059a4b6b507b9ff771901d12035e499b0e8d1cae7d9e5284633e19da6c294e07"
             end

**Comment by cyberflow** [comment] 2016-04-27 09:08
You try to download https://download.elasticsearch.org/kibana/kibana/kibana-2-linux-x64.tar.gz but it's not present. Chef got 404 http error.  Also i'm not sure that cabin 3.1 exist.

**Comment by cyberflow** [comment] 2016-05-04 08:28
I can't reproduce this error on current master cookbook version.

**Comment by drenalin23** [comment] 2016-07-14 17:50
Closing as this is over a year old and can't reproduce in current release and master branch.

**Closed by drenalin23** 2016-07-14 17:50 UTC
